language: go
go: 1.13
go_import_path: https://github.com/kolesa-team/goexiv

cache:
  apt: true
  directories:
    - exiv2

addons:
  apt:
    packages:
      - libexpat-dev
      - libz-dev

env:
  - EXIV2_VERSION=0.27.2

before_install:
  - |
    cd exiv2
    test -d exiv2-${EXIV2_VERSION} && {
      cd exiv2-${EXIV2_VERSION}
    } || {
      wget http://www.exiv2.org/builds/exiv2-${EXIV2_VERSION}-Source.tar.gz
      tar xzf exiv2-${EXIV2_VERSION}-Source.tar.gz
      mv exiv2-Source exiv2-${EXIV2_VERSION}
      cd exiv2-${EXIV2_VERSION}
      ./configure
      make
    }
    sudo make install
    sudo ldconfig
    cd ../..